# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtwonum.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.lineFirstNumber = QtWidgets.QLineEdit(Form)
        self.lineFirstNumber.setGeometry(QtCore.QRect(170, 40, 125, 18))
        font = QtGui.QFont()
        font.setFamily("MeiryoKe_Console")
        font.setPointSize(14)
        self.lineFirstNumber.setFont(font)
        self.lineFirstNumber.setObjectName("lineFirstNumber")
        self.lineSecondNumber = QtWidgets.QLineEdit(Form)
        self.lineSecondNumber.setGeometry(QtCore.QRect(170, 70, 125, 18))
        font = QtGui.QFont()
        font.setFamily("MeiryoKe_Console")
        font.setPointSize(14)
        self.lineSecondNumber.setFont(font)
        self.lineSecondNumber.setObjectName("lineSecondNumber")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(180, 140, 67, 32))
        self.addButton.setObjectName("addButton")
        self.labelFirstNumber = QtWidgets.QLabel(Form)
        self.labelFirstNumber.setGeometry(QtCore.QRect(30, 42, 126, 14))
        font = QtGui.QFont()
        font.setFamily("MeiryoKe_Console")
        font.setPointSize(14)
        self.labelFirstNumber.setFont(font)
        self.labelFirstNumber.setObjectName("labelFirstNumber")
        self.labelSecondNumber = QtWidgets.QLabel(Form)
        self.labelSecondNumber.setGeometry(QtCore.QRect(30, 72, 133, 14))
        font = QtGui.QFont()
        font.setFamily("MeiryoKe_Console")
        font.setPointSize(14)
        self.labelSecondNumber.setFont(font)
        self.labelSecondNumber.setObjectName("labelSecondNumber")
        self.labelAddition = QtWidgets.QLabel(Form)
        self.labelAddition.setGeometry(QtCore.QRect(30, 110, 281, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAddition.sizePolicy().hasHeightForWidth())
        self.labelAddition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MeiryoKe_Console")
        font.setPointSize(14)
        self.labelAddition.setFont(font)
        self.labelAddition.setText("")
        self.labelAddition.setObjectName("labelAddition")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 140, 68, 32))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "Add"))
        self.labelFirstNumber.setText(_translate("Form", "Enter First Number"))
        self.labelSecondNumber.setText(_translate("Form", "Enter Second Number"))
        self.pushButton.setText(_translate("Form", "Quit"))
