# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LTika_ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.lineFirstNumber = QtWidgets.QLineEdit(Form)
        self.lineFirstNumber.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.lineFirstNumber.setObjectName("lineFirstNumber")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(30, 120, 141, 71))
        self.addButton.setCheckable(True)
        self.addButton.setChecked(False)
        self.addButton.setObjectName("addButton")
        self.labelFirstNumber = QtWidgets.QLabel(Form)
        self.labelFirstNumber.setGeometry(QtCore.QRect(20, 20, 308, 21))
        self.labelFirstNumber.setObjectName("labelFirstNumber")
        self.labelAddition = QtWidgets.QLabel(Form)
        self.labelAddition.setGeometry(QtCore.QRect(30, 86, 291, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAddition.sizePolicy().hasHeightForWidth())
        self.labelAddition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAddition.setFont(font)
        self.labelAddition.setText("")
        self.labelAddition.setObjectName("labelAddition")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 150, 71, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addButton.setText(_translate("Form", "ON"))
        self.labelFirstNumber.setText(_translate("Form", "PWMduty:= 0 to 1000000"))
        self.pushButton.setText(_translate("Form", "Quit"))
